---
title: "changeLG_forLinkageMap"
author: "Nurit Eliash"
date: '2022-07-25'
output:
  html_document:
    code_folding: hide
    theme: cerulean
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: yes
      df_print: paged
---
<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

## Aim: changing marker's LG to the main LG in the chromosome

## Load libraries
```{r setup, include=FALSE, warning=FALSE}
library("tidyverse")
library("plyr")
library("dplyr")
library("ggplot2")
library("scales")
library("ggpubr")
library("gridExtra") # for arranging a few plots in one area
#library("grid")
#library("GGally")
library("data.table")
library("stringr")
library("janitor")
library("plotly") # to identify outliers. 
library("sp") # to identify outliers
library("readr") # to extract numbers from a vector
library("tidyr")
knitr::opts_chunk$set(echo = TRUE)
```

## load data
```{r}
# the snps.txt file contains the markers phsycal position, in the order of the markers
# and created via this command , from the map file:
# cut -f 1,2 data.call|awk '(NR>=7)' > snps.txt
snp <- read_delim("/Users/nuriteliash/Documents/GitHub/varroa-linkage-map/varroa_lepmap/data/Q40BIALLDP16HDP40mis.5Chr7/snps.txt")%>% mutate(order = c(1:16986))

# load the map.txt file, containing the markers and their corresponding LG 
map <- read_delim("/Users/nuriteliash/Documents/GitHub/linkage-map-BIGdata/lepmapBigData/Q40BIALLDP16HDP40mis.5Chr7/maf0.2/map3_4_js2/map3_4_js2.txt",col_names = c("LG", "XsqrLG1", "LG2", "XsqrLG2", "LG3", "XsqrLG3", "LG4", "XsqrLG4","LG5", "XsqrLG5"), skip = 1) %>% mutate(order = c(1:16986))
```

```{r}
# state the main LG in each chromosome:
LGs <- data_frame(CHR = c("NW_019211454.1", "NW_019211455.1","NW_019211456.1","NW_019211457.1", "NW_019211458.1","NW_019211459.1", "NW_019211460.1"), LG_new = as.character(c(13,16,2,6,3,1,11)))

# find the single markers (that dont belong to any LG ). 
# these are the markers with LG='0', in the map.txt file
keep <- map %>% dplyr::filter(LG !="0") %>% dplyr::select(c("LG", "order"))

# join the tables based on marker's order. and add the main LG in a new column
# keep only the markers that are linked to linkage groups, based on 'SeperateChromosome2' module
df <- left_join(LGs, snp, by ="CHR") %>%left_join(keep, by="order") %>% na.omit() %>% dplyr::select("#java NEW_LGs JoinSingles2 map=map3_4.txt data=data_f_maf0.2.call iterate=1 lodLimit=2"=LG_new)

# check the number of LGs:
unique(df$`#java NEW_LGs JoinSingles2 map=map3_4.txt data=data_f_maf0.2.call iterate=1 lodLimit=2`)

# distribution of markers in the 7 LGs, after re-asigning them based on the main LG in each chromosome
ggplot(df, aes(`#java NEW_LGs JoinSingles2 map=map3_4.txt data=data_f_maf0.2.call iterate=1 lodLimit=2`)) +
geom_bar(fill = "dodgerblue1", colour = "black") +
  xlab("Chromosome, and its main LG") +
  ylab("Number of markers")

# save as text delimited file. rsync it to flash, and run the OrderMarkers module
#write_delim(df, "/Users/nuriteliash/Documents/GitHub/linkage-map-BIGdata/lepmapBigData/Q40BIALLDP16HDP40mis.5Chr7/maf0.2/map3_4_js2/map3_4_js2_new.txt")

25/7/2022
# now I wait for sasha's script. 
we talked to make a pipeline that will check different parameters of the SeperateChromosome module, so we can find the onse that get the best linkage distirution.





```
