---
title: "explore _vcf_site"
author: "Nurit Eliash"
date: "2/13/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### load libraries
```{r}
library("tidyverse")
library("dplyr")
library("ggplot2")
library("ggpubr")
library("scales")
library("ggpubr")
library("gridExtra")
library("grid")
library("GGally")
library("vcfR")
library("data.table")
library("stringr")
library("janitor")
library("gmodels")
```

## Are there areas on the chromosomes that tend to have high heterozygocity?  
- map sites on chromosomes, and color code by frequency of heterozygosity


load all families
```{r}
vcf <- read.vcfR("/Users/nuriteliash/Documents/GitHub/linkage-map-BIGdata/Q40BIALLDP16HDP40mis.5Chr7.recode.vcf", verbose = FALSE )
vcf

# extract the genotype for each site in each individual
gt <- extract.gt(vcf, element = "GT") 

gt <- as.data.frame(t(gt)) %>%
  rownames_to_column("sample")
# add additional info for each individual
gt_info <- gt %>%
  mutate(fam = str_extract(sample, "[^_]+")) %>%
  mutate(sex = case_when(
    grepl("son", sample) ~ "male",
    grepl("dat|fnd|sis", sample) ~ "female",
    grepl( "_grn_",sample) ~ "ND")) %>%
  mutate(generation = case_when(
    grepl("fnd", sample) ~ "F0",
    grepl("_dat_|sis|_son_", sample) ~ "F1",
    grepl("grn", sample) ~ "F2")) %>%
  mutate(fam_membership = case_when(
    grepl("fnd", sample) ~ "Foundress_mother",
    grepl("_dat_", sample) ~ "Daughter",
    grepl("sis", sample) ~ "Second_daughter",
    grepl("_son_", sample) ~ "Son",
    grepl("grnson", sample) ~ "Grandson",
    grepl("_grndat_", sample) ~ "Granddaughter",
    grepl("_grn_", sample) ~ "Grandson_daughter")) %>%
  dplyr::select(sample, fam, sex, generation, fam_membership, everything())
# t() %>%
#as.data.frame() %>%
#row_to_names(row_number = 1)

#make a subset of three families to play with 
subset_gt <- gt_info %>%
 filter((fam %in% c("63", "46", "110")))
#write_csv(subset_gt, "/Users/nuriteliash/Documents/GitHub/linkage-map-BIGdata/subset_gt.csv")

table <- subset_gt %>%
  
```
