---
title: "figures-for-varroa-pedigree-MS"
output: html_document
date: "2023-02-20"
output:
  html_document:
    code_folding: hide
    theme: cerulean
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: yes
      df_print: paged
---
<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

### load libraries
```{r}
library("tidyverse")
library("dplyr")
library("ggplot2")
library("ggpubr")
library("scales")
library("ggpubr")
library("gridExtra")
library("grid")
library("GGally")
knitr::opts_chunk$set(echo = TRUE)
```

## Heterozygosity per individual
### varroa mite
originally from ~/Documents/GitHub/varroa-linkage-map/R_scripts/LinkMap malesHet.Rmd
```{r}
ind_het <- read_delim("/Users/nuriteliash/Documents/GitHub/varroa-linkage-map/data/vcf_filter/Q40BIALLDP16HDP40mis.5Chr7/Q40BIALLDP16HDP40mis.5Chr7.het", delim = "\t",
           col_names = c("ind","homo_ob", "homo_ex", "nsites", "f"), skip = 1)

# find all 'female' and 'male' 
male <- grep("son",ind_het$ind)
female <- grep("dat|fn|sis",ind_het$ind)

ind_het_sex <- ind_het %>%
  mutate(sex = ifelse(row_number() %in% female, "female", ifelse(row_number() %in% male, "male", "not-determined"))) %>%
  mutate(hom_prop =  homo_ob/nsites) %>%
  mutate(het_prop = (nsites-homo_ob)/nsites) %>%
#keep only adult mites, for which sex is absolutly determined (exclude nymphs and eggs ("not determined"))
 dplyr::filter(sex %in% c("male", "female"))

 # is there a significant difference in the proportion of heterozygotic sites between males and females?5
wil_var <- wilcox.test(het_prop ~ sex, alternative = "two.sided", data = ind_het_sex)
t.test(asin(sqrt(het_prop)) ~ sex, alternative = "two.sided", data = ind_het_sex)
# no significant different (both wilcoxone and welch-test)

# plot heterozygosity proportion, in each sex
p_var <- ggplot(ind_het_sex) +
    geom_boxplot(aes(x = sex, y = het_prop, fill = sex)) + scale_y_continuous() + 
    theme_classic() +
    labs(title = "Varroa mite",
         subtitle = paste("p-value=",  wil_var$p.value)) +
  ylab("Proportion of heterozygotic sites")

# plot heterozygocity proportion, in each individual, color code by sex
p_var_ind <- ggplot(ind_het_sex, aes(x=ind, y=het_prop, color=sex)) + 
    geom_point(size=3) +
    theme_classic() +
    ggtitle("Proportion of heterzygotic sites per individual") +
    xlab("Sample") + 
    ylab("Proportion of het sites")
```

### Honeybee
~/Documents/GitHub/Variant_Calling_bees/R_scripts/male bees.Rmd
```{r}
ind_het_bee <- read_delim("/Users/nuriteliash/Documents/GitHub/Variant_Calling_bees/data/vcf_stats/bee.het", delim = "\t",
           col_names = c("ind","homo_ob", "homo_ex", "nsites", "f"), skip = 1)

# add the sex of each sample, and the proportion of homosyzgotic and hetero sites
sex <- read.csv("/Users/nuriteliash/Documents/GitHub/Variant_Calling_bees/data/meta.csv")
ind_het_bee <- left_join(ind_het_bee,sex, by ="ind") %>%
  mutate(hom_prop =  homo_ob/nsites) %>%
  mutate(het_prop = (nsites-homo_ob)/nsites)
 
# is there a significant difference in the proportion of heterozygotic sites between males and females?5
wil_bee <- wilcox.test(het_prop ~ sex, alternative = "two.sided", data = ind_het_bee)
t.test(asin(sqrt(het_prop)) ~ sex, alternative = "two.sided", data = ind_het_bee)
# no significant different (both wilcoxone and welch-test)

# plot heterozygocity proportion, in each sex
p_bee <- ggplot(ind_het_bee) +
    geom_boxplot(aes(x = sex, y = het_prop, fill = sex)) + scale_y_continuous() + 
    theme_classic() +
    labs(title = "Honeybee",
         subtitle = paste("p-value=",  wil_bee$p.value)) +
  ylab("Proportion of heterozygotic sites")

# plot heterozygosity proportion, in each individual, color code by sex
p_bee_ind <- ggplot(ind_het_bee, aes(x=ind, y=het_prop, color=sex)) + 
    geom_point(size=3) +
    theme_classic() +
    ggtitle("Proportion of heterzygotic sites per bee") +
    xlab("Sample") + 
    ylab("Proportion of het sites")
```

plot varroa and honeybee plots:
```{r}
grid.arrange(top= grid::textGrob("Proportion of heterozygotic sites in males and females", gp=grid::gpar(fontsize=20)), p_bee, p_var, nrow = 1)
```

